name: "Cypress test - Ubuntu"

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Step 1: Install Wine for running Windows executables
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32

      # Step 2: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Print all running processes
      - name: Print all running processes
        run: |
          echo "Listing all running processes..."
          ps aux

      # Step 4: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 5: Install Cypress dependencies
      - name: Install Cypress dependencies
        run: |
          echo "Installing Cypress dependencies..."
          npm install

      # Step 6: Start eController.IntegrationHub.exe using Wine
      - name: Start eController.IntegrationHub.exe with Wine and Run Tests
        run: |
          echo "Starting eController.IntegrationHub.exe using Wine..."
          wine ./ehub/eController.IntegrationHub.exe > stdout.log 2> stderr.log &
          sleep 10  # Allow some time for the server to initialize

          echo "Verifying the application is running..."
          ps aux | grep eController

          echo "Running Cypress tests..."
          npx cypress run

      # Step 7: Display Application Logs
      - name: Display Application Logs
        run: |
          echo "Displaying stdout logs..."
          cat stdout.log || echo "No stdout log found."

          echo "Displaying stderr logs..."
          cat stderr.log || echo "No stderr log found."
