name: "Start eHub as Background"

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Start eController.IntegrationHub.exe in the background
        shell: pwsh
        run: |
          echo "Starting eController.IntegrationHub.exe in the background..."
          Start-Process -FilePath ".\ehub\eController.IntegrationHub.exe" -WorkingDirectory "${{ github.workspace }}\ehub" -NoNewWindow -PassThru
          echo "Application started."

      - name: Verify if the process is running
        shell: pwsh
        run: |
          $process = Get-Process | Where-Object { $_.ProcessName -like "*IntegrationHub*" }
          if ($null -eq $process) {
              throw "eController.IntegrationHub.exe is not running!"
          } else {
              echo "Process is running: $($process.Name)"
          }

      - name: Wait for application to initialize
        shell: pwsh
        run: |
          echo "Waiting for the application to start on http://127.0.0.1:9880..."
          $maxRetries = 50
          $retryCount = 0
          while ($retryCount -lt $maxRetries) {
              try {
                  Invoke-WebRequest -Uri "http://127.0.0.1:9880" -UseBasicParsing -TimeoutSec 5
                  echo "Application is ready!"
                  break
              } catch {
                  echo "Application not ready yet, retrying in 5 seconds..."
                  Start-Sleep -Seconds 5
                  $retryCount++
              }
          }
          if ($retryCount -eq $maxRetries) {
              throw "Application failed to start after $($maxRetries * 5) seconds."
          }

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Cypress dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run
        
