name: "Start eHub and Run Tests"

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start and Verify eController.IntegrationHub.exe in the background
        shell: pwsh
        run: |
          echo "Starting eController.IntegrationHub.exe as a background process..."
          $process = Start-Process -FilePath ".\ehub\eController.IntegrationHub.exe" `
            -WorkingDirectory "${{ github.workspace }}\ehub" `
            -RedirectStandardOutput "${{ github.workspace }}\ehub\stdout.log" `
            -RedirectStandardError "${{ github.workspace }}\ehub\stderr.log" `
            -NoNewWindow -PassThru
          echo "Application started as a background process."
      
          echo "Listing all running processes..."
          Get-Process | Format-Table -AutoSize

          
      # Step 6: Display application-generated logs
      - name: Debug application-generated logs path
        shell: pwsh
        run: |
          echo "Checking for application-generated logs..."
          $logDir = "${{ github.workspace }}\ehub\Logs"
          echo "Listing all files in: $logDir"
          Get-ChildItem -Path $logDir
          $logFile = "$logDir\eController.IntegrationHub..log"
          if (Test-Path $logFile) {
              echo "Found log file at $logFile"
              Get-Content $logFile -Tail 50
          } else {
              throw "Log file not found at $logFile"
          }
      # Step: Print all running processes
      - name: Print all running processes
        shell: pwsh
        run: |
          echo "Listing all running processes..."
          Get-Process | Format-Table -AutoSize

           # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Cypress dependencies
      - name: Install Cypress dependencies
        run: |
          echo "Installing Cypress dependencies..."
          npm install
      
      - name: Start eController.IntegrationHub.exe and Run Tests
        shell: pwsh
        run: |
          # Step 1: Start the application as a background process
          echo "Starting eController.IntegrationHub.exe as a background process..."
          $process = Start-Process -FilePath ".\ehub\eController.IntegrationHub.exe" `
            -WorkingDirectory "${{ github.workspace }}\ehub" `
            -RedirectStandardOutput "${{ github.workspace }}\ehub\stdout.log" `
            -RedirectStandardError "${{ github.workspace }}\ehub\stderr.log" `
            -NoNewWindow -PassThru
          echo "Application started as a background process."
          echo "Running Cypress tests..."
          npx cypress run
      
