name: "Start eHub and Run Tests"

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    timeout-minutes: 30


    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 4: Execute the eController.IntegrationHub.exe application
      - name: Run eController.IntegrationHub.exe
        run: |
          echo "Running eController.IntegrationHub.exe..."
          cd ehub # Navigate to the `ehub` folder
          .\eController.IntegrationHub.exe & # Run the application in the background

            # Step 7 check inside the task list for eHub
      - name: Check if eController.IntegrationHub.exe is running
        shell: pwsh
        run: Get-Process | Where-Object { $_.ProcessName -like "*IntegrationHub*" }
          


      # Step: Print all running processes
      - name: Print all running processes
        shell: pwsh
        run: |
          echo "Listing all running processes..."
          Get-Process | Format-Table -AutoSize

    
            # Step 6: Display application-generated logs
      - name: Debug application-generated logs path
        shell: pwsh
        run: |
          echo "Checking for application-generated logs..."
          $logDir = "${{ github.workspace }}\ehub\Logs"
          echo "Listing all files in: $logDir"
          Get-ChildItem -Path $logDir
          $logFile = "$logDir\eController.IntegrationHub..log"
          if (Test-Path $logFile) {
              echo "Found log file at $logFile"
              Get-Content $logFile -Tail 50
          } else {
              throw "Log file not found at $logFile"
          }

      # Step 7: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 8: Install Cypress dependencies
      - name: Install Cypress dependencies
        run: npm install

      # Step 9: Run Cypress Tests
      - name: Run Cypress Tests
        run: npx cypress run
